services:
  ubuntu:
    image: "ubuntu:latest"
    container_name: "Ubuntu Host"
    hostname: "lin-server"
    privileged: true
    build:
      context: "/ubuntu/.devcontainer"
      dockerfile: "ubuntu.dockerfile"
    networks:
      - admin
      - host
    ports:
      - 22
      - 80
      - 443
    volumes:
      - /source:/target

  api30:
    image: "openjdk:11-jdk-slim"
    container_name: "Android API v30"
    hostname: "Android-v30"
    build:
      context: "/.devcontainer"
      dockerfile: "api30.dockerfile"
    networks:
      - admin
      - host
    ports:
      - 22
      - 80
      - 443
    volumes:
      - type: bind
        source: "D:\\Containers\\Android"
        target: "/vol/dev"
        read_only: false
      - type: bind
        source: "D:\\"
        target: "/vol/admin"
        read_only: false
      - type: bind
        source: "D:\\"
        target: "/vol/storage"
        read_only: false
  
  tailscail:
    image: "tailscail:latest"
    container_name: "Tailscale"
    hostname: "Tailscale-VPN"
    privileged: true
    build:
      context: "/vpn/.devcontainer"
      dockerfile: "tailscale.dockerfile"
    cap_add:
      - net_admin
      - sys_module
    
