services:
  server:
    image: ""
    container_name: "WinServ-01"
    hostname: "WinServ-01"
    privileged: true
    build:
      context: ".\\server\\.devcontainer"
      dockerfile: "servercore.dockerfile"
    networks:
      - admin
      - dev
      - host
      - backend
    ports:
      - 22
      - 80
      - 443
    volumes:
      - type: bind
        source: "Z:\\Docker\\DevContainers\\WinDev\\Windows-Server\\WinServ-01\\volumes\\dev"
        target: "D:\\"
        read_only: false
      - type: bind
        source: "Z:\\Docker\\DevContainers\\WinDev\\Windows-Server\\WinServ-01\\volumes\\storage"
        target: "S:\\"
        read_only: false

  tailscail:
    image: "tailscail"
    container_name: "Tailscale"
    hostname: "tailscale-vpn"
    privileged: true
    build:
      context: ".\\"
      dockerfile: "tailscale.dockerfile"
    network_mode: host
    cap_add:
      - net_admin
      - sys_module
    networks:
      - admin
      - dev
      - host
      - backend
    ports:
      - 22
      - 80
      - 443
    volumes:
      - ""
    
  database:
    image: "sql"
    container_name: "WinSQL-01"
    hostname: "win-database"
    privileged: true
    build:
      context: ".\\database\\.devcontainer"
      dockerfile: "win-db.dockerfile"
    networks:
      - admin
      - backend
    ports:
      - 22
    volumes:
      - type: bind
        source: "Z:\\Docker\\DevContainers\\WinDev\\Windows-Server\\WinSQL-01\\volumes\\data"
        target: "D:\\"
        read_only: false

networks:
  admin: {}
  dev: {}
  host: {}
  backend: {}